branch-defaults:
  master:
    environment: banner-hander-prod
environment-defaults:
  banner-hander-prod:
    branch: null
    repository: null
global:
  application_name: banner-handler
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js running
    on 64bit Amazon Linux/4.4.4
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
